{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 ProFontForPowerline;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red159\green160\blue28;\red180\green36\blue25;
}
{\*\expandedcolortbl;;\csgray\c0;\cssrgb\c68468\c68012\c14208;\cssrgb\c76409\c21698\c12524;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs28 \cf2 \CocoaLigature0 Collecting spacy<3.0.0,>=2.3.5\
  Using cached spacy-2.3.6.tar.gz (5.9 MB)\
  Installing build dependencies ... done\
  Getting requirements to build wheel ... done\
  Installing backend dependencies ... done\
    Preparing wheel metadata ... done\
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking\
  Using cached spacy-2.3.5.tar.gz (5.8 MB)\
  Installing build dependencies ... done\
  Getting requirements to build wheel ... done\
  Installing backend dependencies ... done\
    Preparing wheel metadata ... done\
 INFO: pip is looking at multiple versions of smmap to determine which version is compatible with other requirements. This could take a while.\
Collecting smmap<6,>=3.0.1\
  Downloading smmap-4.0.0-py2.py3-none-any.whl (24 kB)\
\cf3   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/d5/1e/6130925131f639b2acde0f7f18b73e33ce082ff2d90783c436b52040af5a/smmap-3.0.5-py2.py3-none-any.whl\cf2 \
  Downloading smmap-3.0.5-py2.py3-none-any.whl (25 kB)\
\cf4 ERROR: Exception:\cf2 \
\cf4 Traceback (most recent call last):\cf2 \
\cf4   File "/Users/Daniel/miniconda3/envs/latinbert/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main\cf2 \
\cf4     status = self.run(options, args)\cf2 \
\cf4   File "/Users/Daniel/miniconda3/envs/latinbert/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper\cf2 \
\cf4     return func(self, options, args)\cf2 \
\cf4   File "/Users/Daniel/miniconda3/envs/latinbert/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 315, in run\cf2 \
\cf4     requirement_set = resolver.resolve(\cf2 \
\cf4   File "/Users/Daniel/miniconda3/envs/latinbert/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve\cf2 \
\cf4     result = self._result = resolver.resolve(\cf2 \
\cf4   File "/Users/Daniel/miniconda3/envs/latinbert/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve\cf2 \
\cf4     state = resolution.resolve(requirements, max_rounds=max_rounds)\cf2 \
\cf4   File "/Users/Daniel/miniconda3/envs/latinbert/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 383, in resolve\cf2 \
\cf4     raise ResolutionTooDeep(max_rounds)\cf2 \
\cf4 pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000}